name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set Up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Set Up Flutter 3.13.4
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.4'
    - name: Flutter Pub Get
      run: flutter pub get
    - name: Flutter Test
      run: flutter test
    - name: Flutter Build APK
      run: flutter build apk
    - name: Flutter Build AppBundle
      run: flutter build appbundle
