name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set Up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Set Up Flutter 3.16.3
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.3'
    - name: Flutter Pub Get
      run: flutter pub get
    - name: Flutter Build APK
      run: flutter build apk
    - name: Flutter Build AppBundle
      run: flutter build appbundle
    - name: Upload Android APK Release
      uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: ./build/app/outputs/apk/release/app-release.apk
    - name: Upload Android AppBundle Release
      uses: actions/upload-artifact@v2
      with:
        name: android-release
        path: ./build/app/outputs/bundle/release/app-release.aab
